-- 코드를 입력하세요
WITH A AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE * 30 AS MONTH_FEE
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_TYPE = '세단' OR CAR_TYPE = 'SUV'
),
B AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-11-01' BETWEEN START_DATE AND END_DATE
        OR '2022-11-31' BETWEEN START_DATE AND END_DATE
        OR START_DATE BETWEEN '2022-11-01' AND '2022-11-31'
        OR END_DATE BETWEEN '2022-11-01' AND '2022-11-31'
),
C AS (
    SELECT CAR_TYPE, (100 - DISCOUNT_RATE)/100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV') AND DURATION_TYPE = '30일 이상'
)

SELECT A.CAR_ID, A.CAR_TYPE, ROUND((A.MONTH_FEE * C.DISCOUNT_RATE), 0) AS FEE
FROM A
    INNER JOIN C
        ON A.CAR_TYPE = C.CAR_TYPE
WHERE
    A.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM B
    )
    AND ROUND((A.MONTH_FEE * C.DISCOUNT_RATE), 0) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;


    
