-- 코드를 입력하세요
SELECT
    SUBSTRING_INDEX(SALES_YM, '-', 1) AS YEAR,
    SUBSTRING_INDEX(SALES_YM, '-', -1) AS MONTH,
    B.GENDER,
    COUNT(*) AS USERS
FROM (
    SELECT USER_ID, DATE_FORMAT(SALES_DATE, '%Y-%m') AS SALES_YM
    FROM ONLINE_SALE
    GROUP BY USER_ID, SALES_YM
) AS A
    INNER JOIN (
        SELECT USER_ID, GENDER
        FROM USER_INFO 
        WHERE GENDER IS NOT NULL
    ) AS B
    ON A.USER_ID = B.USER_ID
GROUP BY YEAR, MONTH, B.GENDER
ORDER BY YEAR ASC, MONTH ASC, B.GENDER ASC;
