-- 코드를 입력하세요
WITH T AS (
    SELECT CAR_ID, MAX(START_DATE) AS START_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
    GROUP BY CAR_ID
)

SELECT A.CAR_ID, IF(COUNT(T.CAR_ID) = 0, '대여 가능', '대여중') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
    LEFT OUTER JOIN T
    ON A.CAR_ID = T.CAR_ID AND A.START_DATE = T.START_DATE
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC;