-- 코드를 입력하세요
WITH
    T AS (
        SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
        FROM FOOD_ORDER
        WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
        GROUP BY PRODUCT_ID
    )

SELECT T.PRODUCT_ID, F.PRODUCT_NAME, T.AMOUNT * F.PRICE AS TOTAL_SALES
FROM T
    INNER JOIN FOOD_PRODUCT AS F
    ON T.PRODUCT_ID = F.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, T.PRODUCT_ID ASC;