-- 코드를 입력하세요
WITH T AS (
    SELECT CAR_ID, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
),
TT AS (
    SELECT
        A.HISTORY_ID,
        A.CAR_ID,
        (TIMESTAMPDIFF(DAY,A.START_DATE, A.END_DATE) + 1) AS RENTAL_DAY,
        CASE
            WHEN TIMESTAMPDIFF(DAY,A.START_DATE, A.END_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN TIMESTAMPDIFF(DAY,A.START_DATE, A.END_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN TIMESTAMPDIFF(DAY,A.START_DATE, A.END_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE,
        T.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
        INNER JOIN T ON A.CAR_ID = T.CAR_ID
        
),
TTT AS (
    SELECT
        A.HISTORY_ID,
        A.RENTAL_DAY,
        A.DAILY_FEE,
        CASE
            WHEN B.DISCOUNT_RATE IS NULL THEN 1
            ELSE 1 - B.DISCOUNT_RATE/100
        END AS RATE
    FROM TT AS A
        LEFT OUTER JOIN (
            SELECT DURATION_TYPE, DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE CAR_TYPE = '트럭'
        ) AS B
            ON A.DURATION_TYPE = B.DURATION_TYPE
)

SELECT HISTORY_ID, ROUND(RENTAL_DAY * DAILY_FEE * RATE, 0) AS FEE
FROM TTT
ORDER BY FEE DESC, HISTORY_ID DESC;
