-- 코드를 입력하세요
SELECT A.FLAVOR
FROM JULY AS A
    LEFT OUTER JOIN FIRST_HALF AS B
    ON A.SHIPMENT_ID = B.SHIPMENT_ID
GROUP BY FLAVOR
ORDER BY SUM((A.TOTAL_ORDER + IFNULL(B.TOTAL_ORDER, 0))) DESC
LIMIT 3