-- 코드를 입력하세요
SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A, PATIENT AS B, DOCTOR AS C
WHERE
    DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
    AND A.APNT_CNCL_YN = 'N'
    AND A.MCDP_CD = 'CS'
    AND A.PT_NO = B.PT_NO
    AND A.MDDR_ID = C.DR_ID
ORDER BY A.APNT_YMD ASC;