-- 코드를 입력하세요
WITH RECURSIVE T AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM T
    WHERE HOUR < 23
)
SELECT T.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM T
    LEFT OUTER JOIN ANIMAL_OUTS AS B
    ON T.HOUR = DATE_FORMAT(B.DATETIME, '%H')
GROUP BY T.HOUR
ORDER BY T.HOUR ASC;
