-- 코드를 입력하세요
WITH
    T AS(
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        HAVING COUNT(REVIEW_ID) = (
            SELECT MAX(COUNT_REVIEW) AS COUNT_REVIEW_MAX
            FROM (
                SELECT COUNT(REVIEW_ID) AS COUNT_REVIEW
                FROM REST_REVIEW
                GROUP BY MEMBER_ID    
            ) AS B
        ) 
    )
SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS A
    INNER JOIN MEMBER_PROFILE AS B
        ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM T
)
ORDER BY A.REVIEW_DATE ASC, A.REVIEW_TEXT ASC;
