-- 코드를 작성해주세요
SELECT D.ITEM_ID, D.ITEM_NAME, D.RARITY
FROM ITEM_INFO AS A
    RIGHT JOIN (
        SELECT B.ITEM_ID, B.PARENT_ITEM_ID, C.ITEM_NAME, C.RARITY
        FROM ITEM_TREE AS B
            INNER JOIN ITEM_INFO AS C
            ON B.ITEM_ID = C.ITEM_ID
    ) AS D
    ON A.ITEM_ID = D.PARENT_ITEM_ID
WHERE D.PARENT_ITEM_ID IS NOT NULL
    AND A.RARITY = 'RARE'
ORDER BY D.ITEM_ID DESC