WITH
    T AS(
        SELECT B.ITEM_ID
        FROM ITEM_TREE AS A
            RIGHT OUTER JOIN ITEM_TREE AS B
            ON A.ITEM_ID = B.PARENT_ITEM_ID
        WHERE
            A.ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
            AND B.PARENT_ITEM_ID IS NOT NULL
    )
SELECT T.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM T
    INNER JOIN ITEM_INFO AS C
    ON T.ITEM_ID = C.ITEM_ID
ORDER BY T.ITEM_ID DESC;