-- 코드를 입력하세요
WITH TEMP AS (
    SELECT CAR_ID, COUNT(CAR_ID) AS RENTAL_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING RENTAL_COUNT >=5
)

SELECT DATE_FORMAT(START_DATE, '%m') AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    AND CAR_ID
    IN (
        SELECT CAR_ID
        FROM TEMP
    )
GROUP BY MONTH, CAR_ID
HAVING RECORDS != 0
ORDER BY MONTH ASC, CAR_ID DESC;
