-- 코드를 작성해주세요
WITH
    A AS (
        SELECT EMP_NO, SUM(SCORE) AS SCORE_SUM
        FROM HR_GRADE 
        WHERE YEAR = '2022'
        GROUP BY EMP_NO    
    ),
    AA AS (
        SELECT EMP_NO
        FROM A
        WHERE SCORE_SUM = (SELECT MAX(SCORE_SUM) FROM A)
    )
SELECT A.SCORE_SUM AS SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_EMPLOYEES AS B
    INNER JOIN A
    ON B.EMP_NO = A.EMP_NO
WHERE B.EMP_NO IN (SELECT EMP_NO FROM AA)
