-- 코드를 작성해주세요
WITH AA AS (
    SELECT DISTINCT(D.ID)
    FROM DEVELOPERS AS D, SKILLCODES AS S
    WHERE (D.SKILL_CODE & S.CODE) > 0 AND S.CATEGORY = 'Front End'
),
AAA AS (
    SELECT DISTINCT(D.ID)
    FROM DEVELOPERS AS D, SKILLCODES AS S
    WHERE (D.SKILL_CODE & S.CODE) > 0 AND S.NAME = 'Python'
),
A AS (
    SELECT AA.ID
    FROM AA
    WHERE AA.ID IN (SELECT ID FROM AAA)
),
B AS (
    SELECT DISTINCT(D.ID)
    FROM DEVELOPERS AS D, SKILLCODES AS S
    WHERE (D.SKILL_CODE & S.CODE) > 0 AND S.NAME = 'C#'
),
C AS (
    SELECT DISTINCT(D.ID)
    FROM DEVELOPERS AS D, SKILLCODES AS S
    WHERE (D.SKILL_CODE & S.CODE) > 0 AND S.CATEGORY = 'Front End'
),
E AS (
    SELECT ID
    FROM A
    UNION
    SELECT ID
    FROM B
    UNION
    SELECT ID
    FROM C
)
SELECT
    CASE
        WHEN ID IN (SELECT ID FROM A) THEN 'A'
        WHEN ID IN (SELECT ID FROM B) THEN 'B'
        WHEN ID IN (SELECT ID FROM C) THEN 'C'
    END AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS
WHERE ID IN (SELECT ID FROM E)
ORDER BY GRADE ASC, ID ASC