-- 코드를 작성해주세요
WITH
    PYTHON_DEV AS (
        SELECT DISTINCT(D.ID)
        FROM DEVELOPERS AS D, SKILLCODES AS S
        WHERE D.SKILL_CODE & S.CODE > 0 AND S.NAME = 'Python'
    ),
    CSHARP_DEV AS (
        SELECT DISTINCT(D.ID)
        FROM DEVELOPERS AS D, SKILLCODES AS S
        WHERE D.SKILL_CODE & S.CODE > 0 AND S.NAME = 'C#'  
    ),
    FRONTEND_DEV AS (
        SELECT DISTINCT(D.ID)
        FROM DEVELOPERS AS D, (
            SELECT CATEGORY, SUM(CODE) AS SUM_CODE
            FROM SKILLCODES
            GROUP BY CATEGORY
        ) AS S
        WHERE D.SKILL_CODE & S.SUM_CODE > 0 AND S.CATEGORY = 'Front End'  
    )
SELECT
    CASE
        WHEN (D.ID IN (SELECT ID FROM PYTHON_DEV) AND D.ID IN (SELECT ID FROM FRONTEND_DEV)) THEN 'A'
        WHEN D.ID IN (SELECT ID FROM CSHARP_DEV) THEN 'B'
        WHEN D.ID IN (SELECT ID FROM FRONTEND_DEV) THEN 'C'
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS AS D
WHERE
    (D.ID IN (SELECT ID FROM PYTHON_DEV) AND D.ID IN (SELECT ID FROM FRONTEND_DEV))
    OR D.ID IN (SELECT ID FROM CSHARP_DEV)
    OR D.ID IN (SELECT ID FROM FRONTEND_DEV)
ORDER BY GRADE ASC, ID ASC;